### ISSUE TITLE
can not load data and map

### ISSUE THREAD

**Issue by rraabb** [cat-lord/shinyapps#1]
Hi，I downloaded your code and run it in R:

> > runApp("shinyapps-master/STATS19_scanner/")

However, I can not see the data and map in the content, could you help me figure it out? Many thanks!

**Comment by rcatlord** [comment]
Hi rraab,

I couldn’t find the bug. However, I did manage to re-write the app using flexdashboard and it seems to work.

Thanks,

Henry
